WITH

src_data AS (
    SELECT
        ID as ID -- NUMBER
        , EMAILBLACKLISTED as EMAILBLACKLISTED -- BOOLEAN
        , SMSBLACKLISTED as SMSBLACKLISTED -- BOOLEAN
        , CREATEDAT as CREATEDAT -- TEXT
        , MODIFIEDAT as MODIFIEDAT -- TEXT
        , EMAIL as EMAIL -- TEXT
        , LISTIDS as LISTIDS -- TEXT
        , LISTUNSUBSCRIBED as LISTUNSUBSCRIBED -- NUMBER
        , ATTRIBUTES as ATTRIBUTES -- TEXT

    FROM {{ source("BREVO", "CONTACTS")}}
)

SELECT * FROM src_data