WITH

src_data as (
    SELECT
        ORGANIZATION_ID as ORGANIZATION_ID -- TEXT
        , USER_ID as USER_ID -- NUMBER
        , ENTERPRISE as ENTERPRISE -- BOOLEAN
        , EMAIL as EMAIL -- TEXT
        , FIRSTNAME as FIRSTNAME -- TEXT
        , LASTNAME as LASTNAME -- TEXT
        , COMPANYNAME as COMPANYNAME -- TEXT
        , PARSE_JSON(PLAN) AS PLAN
        , PARSE_JSON(PLANVERTICALS) AS PLANVERTICALS
        , RELAY_ENABLED as RELAY_ENABLED -- BOOLEAN
        , RELAY_DATA_USERNAME as RELAY_DATA_USERNAME -- TEXT
        , RELAY_DATA_RELAY as RELAY_DATA_RELAY -- TEXT
        , RELAY_DATA_PORT as RELAY_DATA_PORT -- NUMBER
        , MARKETINGAUTOMATION_KEY as MARKETINGAUTOMATION_KEY -- TEXT
        , MARKETINGAUTOMATION_ENABLED as MARKETINGAUTOMATION_ENABLED -- BOOLEAN
        , ADDRESS_CITY as ADDRESS_CITY -- TEXT
        , ADDRESS_STREET as ADDRESS_STREET -- TEXT
        , ADDRESS_ZIPCODE as ADDRESS_ZIPCODE -- TEXT
        , ADDRESS_COUNTRY as ADDRESS_COUNTRY -- TEXT
    FROM {{ source("BREVO", "ACCOUNTS")}}
),
flattened_data AS (
    SELECT
        ORGANIZATION_ID as ORGANIZATION_ID
        , USER_ID as USER_ID
        , ENTERPRISE as ENTERPRISE
        , EMAIL as EMAIL
        , FIRSTNAME as FIRSTNAME
        , LASTNAME as LASTNAME
        , COMPANYNAME as COMPANYNAME
        , d.value AS PLAN
        , d.value:credits::NUMBER AS PLAN_CREDITS
        , d.value:creditsType::STRING AS PLAN_CREDITSTYPE
        , d.value:type::STRING AS PLAN_TYPE
        , TO_DATE(d.value:startDate) AS PLAN_STARTDATE
        , TO_DATE(d.value:endDate) AS PLAN_ENDDATE
        , t.value AS PLANVERTICALS
        , t.value:credits::STRING AS PLANVERTICALS_CREDITS
        , t.value:name::STRING AS PLANVERTICALS_NAME
        , t.value:planCategory::STRING AS PLANVERTICALS_PLANCATEGORY
        , t.value:planType::STRING AS PLANVERTICALS_PLANTYPE
        , t.value:status::STRING AS PLANVERTICALS_STATUS
        , TO_TIMESTAMP(t.value:startDate) AS PLANVERTICALS_STARTDATE
        , TO_TIMESTAMP(t.value:endDate) AS PLANVERTICALS_ENDDATE
        , t.value:users:purchasedSeats::NUMBER AS PLANVERTICALS_USERS_PURCHASEDSEATS
        , t.value:users:usedSeats::NUMBER AS PLANVERTICALS_USERS_USEDSEATS
        , RELAY_ENABLED as RELAY_ENABLED
        , RELAY_DATA_USERNAME as RELAY_DATA_USERNAME
        , RELAY_DATA_RELAY as RELAY_DATA_RELAY
        , RELAY_DATA_PORT as RELAY_DATA_PORT
        , MARKETINGAUTOMATION_KEY as MARKETINGAUTOMATION_KEY
        , MARKETINGAUTOMATION_ENABLED as MARKETINGAUTOMATION_ENABLED
        , ADDRESS_CITY as ADDRESS_CITY
        , ADDRESS_STREET as ADDRESS_STREET
        , ADDRESS_ZIPCODE as ADDRESS_ZIPCODE
        , ADDRESS_COUNTRY as ADDRESS_COUNTRY
    FROM src_data,
    LATERAL FLATTEN(input => PLAN) d,
    LATERAL FLATTEN(input => PLANVERTICALS) t
)

SELECT * FROM flattened_data