WITH

src_data AS (
    SELECT
        ID as ID -- NUMBER
        , NAME as NAME -- TEXT
        , FOLDERID as FOLDERID -- NUMBER
        , UNIQUESUBSCRIBERS as UNIQUESUBSCRIBERS -- NUMBER
        , TOTALBLACKLISTED as TOTALBLACKLISTED -- NUMBER
        , TOTALSUBSCRIBERS as TOTALSUBSCRIBERS -- NUMBER

    FROM {{ source("BREVO", "CONTACTS_LISTS") }}

)

SELECT * FROM src_data